const ADD_TRANSACTION = "ADD_TRANSACTION";
const END_MINING = "END_MINING";
const MY_ADDRESS = "MY_ADDRESS";
const BLOCKSIZE_TRANSACTIONS = 100;
const CURRENT_DIFFICULTY = 4;
const FREE_COINS = 10;
const ADD_NEW_NODE = "ADD_NEW_NODE";
const MINING_REWARD = 10;

module.exports.ADD_TRANSACTION = ADD_TRANSACTION;
module.exports.END_MINING = END_MINING;
module.exports.MY_ADDRESS = MY_ADDRESS;
module.exports.BLOCKSIZE_TRANSACTIONS = BLOCKSIZE_TRANSACTIONS;
module.exports.CURRENT_DIFFICULTY = CURRENT_DIFFICULTY;
module.exports.FREE_COINS = FREE_COINS;
module.exports.ADD_NEW_NODE = ADD_NEW_NODE;
module.exports.MINING_REWARD = MINING_REWARD;