const ADD_TRANSACTION = "ADD_TRANSACTION";
const END_MINING = "ENDMINING";
const MY_ADDRESS = "MYADDRESS";

module.exports.ADD_TRANSACTION = ADD_TRANSACTION;
module.exports.END_MINING = END_MINING;
module.exports.MY_ADDRESS = MY_ADDRESS;

