const ADD_TRANSACTION = "ADD_TRANSACTION";
const END_MINING = "ENDMINING";
const MY_ADDRESS = "MYADDRESS";
const BLOCKSIZE_TRANSACTIONS = 2;
const CURRENT_DIFFICULTY = 4;
const FREE_COINS = 10;


module.exports.ADD_TRANSACTION = ADD_TRANSACTION;
module.exports.END_MINING = END_MINING;
module.exports.MY_ADDRESS = MY_ADDRESS;
module.exports.BLOCKSIZE_TRANSACTIONS = BLOCKSIZE_TRANSACTIONS;
module.exports.CURRENT_DIFFICULTY = CURRENT_DIFFICULTY;
module.exports.FREE_COINS = FREE_COINS;

